const formsdata = [{
        id:"name",
        label:"Name",
        type: "text",
        placeholder:"enter your name",
        required: true,
    },
    {
        id:"email",
        label:"Email",
        type: "email",
        placeholder:"enter your email",
        required: true,
    },
    {
        id:"password",
        label:"Password",
        type: "password",
        placeholder:"enter your password",
        required: true,
    },
    {
        id:"phone",
        label:"Phone",
        type: "tel",
        placeholder:"enter your phone number",
        required: false,
    },
    {
        id:"age",
        label:"Age",
        type: "number",
        placeholder:"enter your age",
        required: false,
    },
    ]